[2025-02-24T11:45:29.774+0530] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: fraud_detection_processing_dag.engineer_features manual__2025-02-24T05:35:11.806439+00:00 [queued]>
[2025-02-24T11:45:29.777+0530] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: fraud_detection_processing_dag.engineer_features manual__2025-02-24T05:35:11.806439+00:00 [queued]>
[2025-02-24T11:45:29.777+0530] {taskinstance.py:1361} INFO - Starting attempt 4 of 6
[2025-02-24T11:45:29.782+0530] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): engineer_features> on 2025-02-24 05:35:11.806439+00:00
[2025-02-24T11:45:29.786+0530] {standard_task_runner.py:57} INFO - Started process 12974 to run task
[2025-02-24T11:45:29.789+0530] {standard_task_runner.py:84} INFO - Running: ['airflow', 'tasks', 'run', 'fraud_detection_processing_dag', 'engineer_features', 'manual__2025-02-24T05:35:11.806439+00:00', '--job-id', '121', '--raw', '--subdir', 'DAGS_FOLDER/data_pipeline_dag.py', '--cfg-path', '/var/folders/kz/_l5jq2xx6db29k_3xyv2j8n40000gp/T/tmpz7xjwrw8']
[2025-02-24T11:45:29.790+0530] {standard_task_runner.py:85} INFO - Job 121: Subtask engineer_features
[2025-02-24T11:45:29.812+0530] {task_command.py:416} INFO - Running <TaskInstance: fraud_detection_processing_dag.engineer_features manual__2025-02-24T05:35:11.806439+00:00 [running]> on host ninja-its-macbook-air-90.local
[2025-02-24T11:45:29.899+0530] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='fraud_detection_processing_dag' AIRFLOW_CTX_TASK_ID='engineer_features' AIRFLOW_CTX_EXECUTION_DATE='2025-02-24T05:35:11.806439+00:00' AIRFLOW_CTX_TRY_NUMBER='4' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-02-24T05:35:11.806439+00:00'
[2025-02-24T11:45:29.899+0530] {data_pipeline_dag.py:156} INFO - Engineering features...
[2025-02-24T11:45:29.902+0530] {data_pipeline_dag.py:160} ERROR - Processed data file not found at /Users/nc25577_suryateja/Documents/air_pro/input_files/processed_df.csv
[2025-02-24T11:45:29.902+0530] {data_pipeline_dag.py:196} ERROR - Error in feature engineering: Processed data file not found at /Users/nc25577_suryateja/Documents/air_pro/input_files/processed_df.csv
[2025-02-24T11:45:29.902+0530] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/Users/nc25577_suryateja/Documents/air_pro/venv/lib/python3.9/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/Users/nc25577_suryateja/Documents/air_pro/airflow/dags/data_pipeline_dag.py", line 161, in engineer_features
    raise FileNotFoundError(f"Processed data file not found at {input_path}")
FileNotFoundError: Processed data file not found at /Users/nc25577_suryateja/Documents/air_pro/input_files/processed_df.csv
[2025-02-24T11:45:29.908+0530] {taskinstance.py:1400} INFO - Marking task as UP_FOR_RETRY. dag_id=fraud_detection_processing_dag, task_id=engineer_features, execution_date=20250224T053511, start_date=20250224T061529, end_date=20250224T061529
[2025-02-24T11:45:29.912+0530] {standard_task_runner.py:104} ERROR - Failed to execute job 121 for task engineer_features (Processed data file not found at /Users/nc25577_suryateja/Documents/air_pro/input_files/processed_df.csv; 12974)
[2025-02-24T11:45:29.925+0530] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2025-02-24T11:45:29.935+0530] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
